dataset:
  num_workers: 2
  data_path: './data'
  batch_size: 64
  image_size: 32

model:
  in_channels: 3
  hidden_size: 160
  z_size: 32
  k: 1
  kl_min: 0.25
  num_hidden_layers: 2
  num_blocks: 2

training:
  optimizer:
    learning_rate: 0.001
  current_checkpoint: "./runs/"
  checkpoints_frequency: 10 # epochs
  n_epochs: 1000

save_model:
  checkpoint_path: "./"


validation:
  enabled: true
  every: 4 # epochs
  batch_size: 8

generic:
  seed: 0
  workers: 2

