dataset:
  num_workers: 2
  data_path: './data'
  batch_size: 64
  image_size: 32

model:
  in_channels: 3
  hidden_size: 160
  z_size: 32
  k: 1
  kl_min: 0.25
  num_hidden_layers: 2
  num_blocks: 2

training:
  optimizer:
    learning_rate: 0.001

  checkpoints_path: "./checkpoints"
  checkpoints_frequency: 1 # epochs
  batch_size: 8
  n_epochs: 250


validation:
  enabled: true
  every: 4 # epochs
  batch_size: 8

generic:
  seed: 0
  workers: 2

